### ISSUE TITLE
Creating cluster fails with NIP not found

### ISSUE THREAD

**Issue by galderz** [cmoulliard/gce-openshifter#2]
Doc says setting DNS is optional. Without doing it I get:

```
INFO:DNS(google):Looking up zone
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/libcloud/dns/drivers/google.py", line 107, in get_zone
    response = self.connection.request(request, method='GET').object
  File "/usr/lib/python3.6/site-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python3.6/site-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python3.6/site-packages/libcloud/common/google.py", line 280, in parse_body
    raise ResourceNotFoundError(message, self.status, code)
libcloud.common.google.ResourceNotFoundError: {'domain': 'global', 'reason': 'notFound', 'message': "The 'parameters.managedZone' resource named 'nip' does not exist."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 47, in create
    openshifter.create()
  File "/root/openshifter/__init__.py", line 49, in create
    self.provision()
  File "/root/openshifter/__init__.py", line 29, in provision
    driver.create(cluster)
  File "/root/dns/google.py", line 24, in create
    zone = self.dns.get_zone(self.deployment['dns']['zone'])
  File "/usr/lib/python3.6/site-packages/libcloud/dns/drivers/google.py", line 111, in get_zone
    zone_id=zone_id)
libcloud.dns.types.ZoneDoesNotExistError: <ZoneDoesNotExistError in <libcloud.dns.drivers.google.GoogleDNSDriver object at 0x7f2ede2c6828>, zone_id=nip, value=>
```

**Comment by cmoulliard** [comment]
Can you share your config ? Is the dns-zone defined as such - https://github.com/openshift-evangelists/openshifter/blob/master/example/sample.yml#L14 ?

**Comment by galderz** [comment]
Fixed it using different configuration.
