### ISSUE TITLE
No support for suffix

### ISSUE THREAD

**Issue by galderz** [cmoulliard/gce-openshifter#3]
Since there's no `osevg/openshifter:15` image in place, I'm force to use latest which seems to require `suffix` configuration.

What am I supposed to put there?

```
root/.google_libcloud_auth.my-sa-1@openshifter-sample-galder-zama.iam.gserviceaccount.com'
INFO:DNS(google):Looking up zone
Traceback (most recent call last):
  File "../main.py", line 14, in <module>
    openshifter.cli.cli()
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/openshifter/cli.py", line 47, in create
    openshifter.create()
  File "/root/openshifter/__init__.py", line 49, in create
    self.provision()
  File "/root/openshifter/__init__.py", line 29, in provision
    driver.create(cluster)
  File "/root/dns/google.py", line 28, in create
    name = name + '.' + self.deployment.name + '.' + self.deployment['dns']['suffix'] + '.'
KeyError: 'suffix'
```

**Comment by cmoulliard** [comment]
Here is the suffix definition : https://github.com/openshift-evangelists/openshifter/blob/master/example/sample.yml#L15

**Comment by galderz** [comment]
Thanks, I can read ;)

What I'm really trying to ask is this: do I need to come up with my own domain somehow to run OpenShift on GCP?

**Comment by galderz** [comment]
Turns out I don't. Thanks
